### ISSUE TITLE
Mogelijke waarden van de eigenschap 'type' 

### ISSUE THREAD

**Issue by StijnClaes** [Informatievlaanderen/OSLOthema-incentiveringsplatform#1]
Bij meerdere entiteiten wordt er een eigenschap 'type' gedefinieerd, namelijk o.a. bij 'Beloning', 'Bewijs', 'Bewijslevering' en 'Criteriumvereiste' enzovoort. Er werd bewust voor gekozen om geen vooraf gedefinieerde lijst van mogelijke waarden hiervoor op te lijsten. 

Uit de praktijk lijkt het echter niet evident om dit 'type' in te vullen. De vraag stelt zich of dit al dan niet behouden moet worden.

Indien we toch een poging doen, zouden we eventueel volgende waarden voor 'type' als voorbeeld kunnen bedenken:
- Bij 'Beloning' zou het type misschien deze waarden kunnen hebben: 'digitale munt', 'fysieke munt', 'naturaprijs', 'fysieke tegenwaarde' (bijv. wanneer de beloning een geplante boom betreft) ...
- Bij 'Bewijs' zou het type misschien deze waarden kunnen hebben: 'fysieke overdracht' (bijv. 1 kg ingezameld zwerfvuil afgeven), 'automatische registratie' (bijv. scan aan een sensor), 'fysieke test' (bijv. bij een alcoholmeting)...
- Bij 'Bewijslevering' idem als bij 'Bewijs', maar dan stelt de vraag of je dit twee keer moet registreren (hier misschien schrappen?)
- Bij 'Criteriumvereiste' zou het type misschien deze waarden kunnen hebben: 'geografische voorwaarde', 'fysieke voorwaarde', 'administratieve voorwaarde'...

**Comment by VincentFeremans** [comment]
Bij ieder van deze klassen werd een ConceptScheme toegevoegd. Deze biedt voldoende vrijheid tijdens de implementatie van het datamodel om naar eigen belang/nood codelijsten op te stellen bij de respectievelijke eigenschappen. Indien gevraagd door het kernteam kunnen deze codelijsten ook door Digitaal Vlaanderen worden beheerd.​

Verder werd er in overleg met het kernteam besloten om 'BewijsType' bij 'Bewijslevering' te verwijderen.
