### ISSUE TITLE
Dekt de term 'Bedrag' de lading?

### ISSUE THREAD

**Issue by StijnClaes** [Informatievlaanderen/OSLOthema-incentiveringsplatform#2]
Wanneer bijv. voor een beloning een Waarde gedefinieerd wordt, dan gebeurt dit aan de hand van een type 'Bedrag', zijnde een Eenheid en een Aantal.

Is de term 'Bedrag' de juiste term om hier te gebruiken? Dekt deze de lading, namelijk het feit dat er een Aantal (getal) verwacht wordt en een eenheid of valuta.

Daarnaast: bij de Waarde van Beloning of de TotaalWaarde van het Stimulansaanbod, verwijst dit naar iets wat je min of meer monetair kan beschouwen (1 euro, 2 digitale munten...). Bij 'Bewijs' wordt echter een Waarde van het type 'Bedrag' verwacht en daar kan het bijv. gaan over '1 kg ingezameld zwerfvuil' of '1 scan door een sensor'. Kan je hier dan ook nog dezelfde term voor gebruiken?

**Comment by VincentFeremans** [comment]
'KwantitativeWaarde' werd toegevoegd en gelinkt aan 'Bedrag' via overerving. Hierdoor werd er besloten om 'Bedrag' overal te vervangen met dit nieuwe datatype aangezien deze allesomvattend is.  Zo kan men dus met één datatype over een aantal, eenheid en valuta spreken.
